// Generated by scripts/generate-mastery-kits.mjs. Do not edit by hand.
// Uses only Node.js built-ins and never reads a reference solution directory.

import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const candidateRoot = existsSync(join(projectRoot, "starter"))
  ? join(projectRoot, "starter")
  : projectRoot;
const read = (path) => readFileSync(join(candidateRoot, path), "utf8");

const html = read("index.html");
const withoutComments = html.replace(/<!--[\s\S]*?-->/g, "");
const openTags = (name, source = withoutComments) =>
  [...source.matchAll(new RegExp("<" + name + "\\b[^>]*>", "gi"))].map((match) => match[0]);
const blocks = (name, source = withoutComments) =>
  [...source.matchAll(new RegExp("<" + name + "\\b[^>]*>([\\s\\S]*?)<\\/" + name + ">", "gi"))];
const attr = (markup, name) => {
  const match = markup.match(new RegExp(
    "\\b" + name + "\\s*=\\s*(?:\"([^\"]*)\"|'([^']*)'|([^\\s>]+))",
    "i"
  ));
  return match ? (match[1] ?? match[2] ?? match[3]) : null;
};
const text = (markup) => markup.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();

const css = read("styles.css");
test("uses article landmarks and working descriptive jump links", () => {
  for (const landmark of ["header", "main", "footer", "article"]) {
    assert.equal(openTags(landmark).length, 1, "use one " + landmark);
  }
  assert.equal(openTags("h1").length, 1);
  const nav = openTags("nav")[0] ?? "";
  assert.ok(attr(nav, "aria-label"), "label the navigation");
  const ids = new Set(openTags("[a-z][a-z0-9-]*").map((tag) => attr(tag, "id")).filter(Boolean));
  const jumpLinks = openTags("a").filter((tag) => (attr(tag, "href") ?? "").startsWith("#"));
  assert.ok(jumpLinks.length >= 3, "include recipe jumps and return-to-start");
  for (const link of jumpLinks) assert.ok(ids.has(attr(link, "href").slice(1)), "missing target for " + attr(link, "href"));
});

test("marks up the resilient recipe figure", () => {
  const figure = blocks("figure")[0]?.[1] ?? "";
  const image = openTags("img", figure)[0] ?? "";
  assert.match(attr(image, "src") ?? "", /mandazi\.svg$/);
  assert.ok((attr(image, "alt") ?? "").trim().length >= 12, "write useful alt text");
  assert.equal(attr(image, "width"), "640");
  assert.equal(attr(image, "height"), "400");
  assert.ok(text(blocks("figcaption", figure)[0]?.[1] ?? "").length >= 8);
  assert.match(css, /img\s*{[^}]*max-width\s*:\s*100%[^}]*height\s*:\s*auto/si);
});

test("uses lists and machine-readable durations", () => {
  const ingredients = blocks("section").find((block) => attr(block[0], "id") === "ingredients")?.[1] ?? "";
  const method = blocks("section").find((block) => attr(block[0], "id") === "method")?.[1] ?? "";
  assert.ok(blocks("ul", ingredients).some((list) => blocks("li", list[1]).length >= 3));
  assert.ok(blocks("ol", method).some((list) => blocks("li", list[1]).length >= 3));
  const durations = new Set(openTags("time").map((tag) => attr(tag, "datetime")));
  assert.ok(durations.has("PT20M"));
  assert.ok(durations.has("PT25M"));
});
